#!/usr/bin/env bash
# script that will display information about subdomains. 
# shellcheck disable=SC2086

if [ $# -eq 2 ]
then
    domain="$1"
    subdomain="$2.$domain"
    ip=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
    record=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
    echo  "The subdomain $2 is a $record record and points to $ip"
elif [ $# -eq 1 ]
then
    for subdomain in 'www' 'lb-01' 'web-01' 'web-02'
    do  
        domain="$1"
        ip=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')
        record=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')
        echo  "The subdomain $subdomain is a $record record and points to $ip"
    done
fi
