#!/usr/bin/env bash
#This script is displaying "Holberton School" 10 times
# ----------------------------
string="Holberton School"
for ((i=0; i<10; i++)); do
    echo "$string"
done
# ----------------------------
