#!/usr/bin/env bash
# Set custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
# Enable PORT 80
sudo ufw allow 'Nginx HTTP'
# Create the file and add string
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
# redirection
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx start