#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80 default_server;
    location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
    internal;
    }
    add_header X-Served-By $HOSTNAME;
    listen [::]:80 default_server;
    root   /var/www//html;
    index index.nginx-debian.html index.nginx-debian.html;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
