#!/usr/bin/env bash
# The ball in never actually thrown at all
while IFS=":" read -r USERNAME PASSWORD ID GROUP_ID INFO HOME_DIR SHELL
do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIR \
and rides $SHELL. $ID's place is protected by the passcode $PASSWORD, more info \
about the user here: $INFO"
done < /etc/passwd
