#!/usr/bin/env bash
#Basic while loop with  if condition

counter=0
while [ $counter -lt 10 ];
do
   echo "Holberton School"
   if [ $counter -eq 8 ]; then
      echo "Hi"
      fi
      ((counter++))
done

