#!/usr/bin/env bash
#Basic while loop with  if condition

counter=1
while [ $counter -lt 11 ]
do
	if [ $counter -eq 4 ]; then
	   echo "bad luck"
	   elif [ $counter -eq 8 ]; then
	   	echo "good luck"
		else
			echo "Holberton School"
			fi
			((counter++))
done
