#!/usr/bin/env bash
#Basic while loop with  if condition

counter=1
while [ $counter -le 20 ];
do
	echo "$counter"
	case $counter in
	4)
		echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
			17)
				echo "bad luck from Italy";;
				esac
				((counter++))
done
