#!/usr/bin/env bash
#This script will display the time
#display hours from 0 to 12
#display minutes from 1 to 59

i=1
counter=1
echo "Hour: 0"
while [ $i -le 59 ];
do
	echo "$i"
	if [ $counter -eq 13 ] && [ $i == 59 ]; then
	   break
	   fi
	   case $i in
	   59)
		let i=1
		    echo "Hour: $counter"
		    	 ((counter++))
				echo "$i"
				esac
				((i++))
done