#!/usr/bin/env bash
#Configures an Ubuntu server with the below requirements

FILE="/etc/hosts"
TFILE="/etc/hoststemp"
cp "$FILE" "$TFILE"
sed -i -e 's/127.0.0.1/127.0.0.2/g' "$TFILE"
echo "8.8.8.8 facebook.com" >> "$TFILE"
cp "$TFILE" "$FILE"