#!/usr/bin/env bash
# Change to nginx user and enable 8080 ports on conf file
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
pkill apache2

sudo -u nginx service nginx restart